POST http://localhost:8000/create-company-account HTTP/1.1
content-Type: application/json

{
    "name": "My Super Company 2",
    "VAT": "BE12345678902",
    "email": "super@company.com",
    "adress": "Company City - 1000",
    "IBAN": "BE.123.456.789"
}

###

POST http://localhost:8000/create-customer-account HTTP/1.1
# Create Customer Account
content-type: application/json

{
    "IBAN": "BE.987.654.322",
    "name": "Happy Customer",
    "email": "happy@customer.com",
    "adress": "Customer City - 1000",
    "company": "BE12345678902"
}

###

POST http://localhost:8000/create-quote HTTP/1.1
# Create Quote
content-type: application/json

{
    "company": "BE12345678902",
    "quantity": 1,
    "price": "999999",
    "currency": "USD"
}

###

POST http://localhost:8000/create-subscription HTTP/1.1
# Create Quote
content-type: application/json

{
    "customer": "BE.987.654.322",
    "quote": 5
}

###

POST http://localhost:8000/update-subscription HTTP/1.1
# Create Quote
content-type: application/json

{
    "subscription": 5,
    "status": "accepted"
}

###

POST http://localhost:8000/pending-invoices HTTP/1.1
# Create Quote
content-type: application/json

{
    "customer": "BE.987.654.322"
}

###

POST http://localhost:8000/update-invoice HTTP/1.1
# Create Quote
content-type: application/json

{
    "invoice": 1,
    "received": 98.99,
    "card": ""
}

###

POST http://localhost:8000/company-statistics HTTP/1.1
# Create Quote
content-type: application/json

{
    "company": "BE12345678902"
}

###

POST http://localhost:8000/cron-send-invoices HTTP/1.1
# Create Quote
content-type: application/json

{
    
}

###

POST http://localhost:8000/ask-classement HTTP/1.1
# Create Quote
content-type: application/json

{
    "vat": "BE12345678901"
}